version: '3'
services:
  work-machine:
    build: .
    restart: unless-stopped
    container_name: work-machine
    hostname: work-machine
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
