---
- name: setup work machine
  hosts: all

  tasks:
    - include_vars: vars/user.yml
    - include: tasks/base.yml
    - include: tasks/tools.yml
    - include: tasks/user.yml
  handlers:
    - include: handlers/handlers.yml
