---
- name: "Enable NOPASSWD: ALL in /etc/sudoers"
  ansible.builtin.copy:
    dest: /etc/sudoers.d/wheel
    content: "%wheel ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: 0440
  tags:
    - user

- name: Create group for intended user
  ansible.builtin.group:
    name: "{{ user.login }}"
    state: present
  tags:
    - user

- name: Create intended user
  ansible.builtin.user:
    name: "{{ user.login }}"
    groups: "{{ user.groups }}"
    shell: /bin/bash
    home: "/home/{{ user.login }}"
    state: present
  tags:
    - user

- name: Setup authorized_keys for all intended users
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ user.ssh_pubkey }}"
    state: present
  loop:
    - root
    - "{{ user.login }}"
  when: wsl2 is false
  tags:
    - user

- name: Provision .gitconfig
  ansible.builtin.template:
    src: gitconfig
    dest: "{{ item }}"
    owner: "{{ user.login }}"
    group: "{{ user.login }}"
    mode: 0600
  loop:
    - "/home/{{ user.login }}/.gitconfig"
  tags:
    - user

- name: Provision tmux.conf
  ansible.builtin.template:
    src: tmux.conf
    dest: "{{ item }}"
    owner: "{{ user.login }}"
    group: "{{ user.login }}"
    mode: 0600
  loop:
    - "/home/{{ user.login }}/tmux.conf"
  tags:
    - user

- name: Setup bashrc
  ansible.builtin.template:
    src: bashrc
    dest: /etc/profile.d/bashrc.sh
    mode: 0644
  tags:
    - user

- name: Setup environment variables
  ansible.builtin.template:
    src: vars.sh
    dest: /etc/profile.d/vars.sh
    mode: 0644
  tags:
    - user
