---
- name: create group for intended user
  group:
    name: "{{ login }}"
  tags: user

- name: create intended user
  user:
    name: "{{ login }}"
    group: "{{ login }}"
    shell: /bin/bash
    home: "/home/{{ login }}"
  tags: user

- name: setup authorized_keys for all intended users
  authorized_key:
    user: "{{ item }}"
    key: "{{ ssh_pubkey }}"
    state: present
  with_items:
    - root
    - "{{ login }}"
  tags: user

- name: provision .gitconfig
  template:
    src: gitconfig
    dest: "{{ item }}"
  with_items:
    - /root/.gitconfig
    - "/home/{{ login }}/.gitconfig"
  tags: user

- name: setup bashrc
  template:
    src: bashrc
    dest: /etc/profile.d/bashrc.sh
    mode: 0644
  tags: user

- name: setup environment variables
  template:
    src: vars.sh
    dest: /etc/profile.d/vars.sh
    mode: 0644
  tags: user

- name: provision tmux.conf
  template:
    src: tmux.conf
    dest: "{{ item }}"
  with_items:
    - /root/tmux.conf
    - "/home/{{ login }}/tmux.conf"
  tags: user
