---
- name: create group for intended user
  group:
    name: "{{ login }}"

- name: create intended user
  user:
    name: "{{ login }}"
    groups: ["{{ login }}", "users", "wheel"]
    shell: /bin/bash
    home: "/home/{{ login }}"

- name: setup authorized_keys for all intended users
  authorized_key:
    user: "{{ item }}"
    key: "{{ ssh_pubkey }}"
    state: present
  loop:
    - root
    - "{{ login }}"

- name: provision .gitconfig
  template:
    src: gitconfig
    dest: "{{ item }}"
  loop:
    - /root/.gitconfig
    - "/home/{{ login }}/.gitconfig"

- name: setup bashrc
  template:
    src: bashrc
    dest: /etc/profile.d/bashrc.sh
    mode: 0644

- name: setup environment variables
  template:
    src: vars.sh
    dest: /etc/profile.d/vars.sh
    mode: 0644

- name: provision tmux.conf
  template:
    src: tmux.conf
    dest: "{{ item }}"
  loop:
    - /root/tmux.conf
    - "/home/{{ login }}/tmux.conf"
