---
- name: "Enable NOPASSWD: ALL in /etc/sudoers"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    regexp: "NOPASSWD:.+ALL"
  tags:
    - user

- name: Create group for intended user
  ansible.builtin.group:
    name: "{{ user.login }}"
    state: present
  tags:
    - user

- name: Create intended user
  ansible.builtin.user:
    name: "{{ user.login }}"
    groups: "{{ user.groups }}"
    shell: /bin/bash
    home: "/home/{{ user.login }}"
    state: present
  tags:
    - user

- name: Configure user directories for systemd
  ansible.builtin.file:
    path: "/home/{{ user.login }}/.config/systemd/user"
    state: directory
    owner: "{{ user.login }}"
    group: "{{ user.login }}"
    mode: 0755
    recurse: true
  tags:
    - user

- name: Configure ssh-agent.service
  ansible.builtin.template:
    src: ssh-agent.service.j2
    dest: "/home/{{ user.login }}/.config/systemd/user/ssh-agent.service"
    owner: "{{ user.login }}"
    group: "{{ user.login }}"
    mode: 0644
  tags:
    - user

- name: Setup authorized_keys for all intended users
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ user.ssh_pubkey }}"
    state: present
  loop:
    - root
    - "{{ user.login }}"
  when: wsl2 is false
  tags:
    - user

- name: Provision dotfiles
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: 0600
  loop:
    - {owner: root, group: root, src: bashrc.j2, dest: "/root/.bashrc"}
    - {owner: "{{ user.login }}", group: "{{ user.login }}", src: bashrc.j2, dest: "/home/{{ user.login }}/.bashrc"}
    - {owner: root, group: root, src: tmux.conf.j2, dest: "/root/.tmux.conf"}
    - {owner: "{{ user.login }}", group: "{{ user.login }}", src: tmux.conf.j2, dest: "/home/{{ user.login }}/.tmux.conf"}
    - {owner: "{{ user.login }}", group: "{{ user.login }}", src: gitconfig.j2, dest: "/home/{{ user.login }}/.gitconfig"}
  tags:
    - user

- name: Setup environment variables
  ansible.builtin.template:
    src: vars.sh
    dest: /etc/profile.d/vars.sh
    mode: 0644
  tags:
    - user
