---
- name: comment out ALL requiring password in /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: "# %wheel  ALL=(ALL)       ALL"
    regexp: "^%wheel  ALL=(ALL)       ALL"
  tags:
    - users

- name: "enable NOPASSWD: ALL in /etc/sudoers"
  lineinfile:
    path: /etc/sudoers
    line: "%wheel        ALL=(ALL)       NOPASSWD: ALL"
    regexp: "^# %wheel        ALL=(ALL)       NOPASSWD: ALL"
  tags:
    - users

- name: create group for intended user
  group:
    name: "{{ login }}"
  tags:
    - user

- name: create intended user
  user:
    name: "{{ login }}"
    groups: ["{{ login }}", "users", "wheel"]
    shell: /bin/bash
    home: "/home/{{ login }}"
  tags:
    - user

- name: setup authorized_keys for all intended users
  authorized_key:
    user: "{{ item }}"
    key: "{{ ssh_pubkey }}"
    state: present
  loop:
    - root
    - "{{ login }}"
  tags:
    - user

- name: provision .gitconfig
  template:
    src: gitconfig
    dest: "{{ item }}"
    owner: "{{ login }}"
    group: "{{ login }}"
  loop:
    - "/home/{{ login }}/.gitconfig"
  tags:
    - user

- name: setup bashrc
  template:
    src: bashrc
    dest: /etc/profile.d/bashrc.sh
    mode: 0644
  tags:
    - user

- name: setup environment variables
  template:
    src: vars.sh
    dest: /etc/profile.d/vars.sh
    mode: 0644
  tags:
    - user

- name: provision tmux.conf
  template:
    src: tmux.conf
    dest: "{{ item }}"
    owner: "{{ login }}"
    group: "{{ login }}"
  loop:
    - "/home/{{ login }}/tmux.conf"
  tags:
    - user
