---
docker_package_name: "docker-ce"
docker_version_centos: "18.03.1.ce-1.el7.centos"
docker_version_debian: "17.12.0~ce-0~{{ ansible_lsb.id|lower }}"
docker_machine_package_name: "docker-machine-{{ ansible_system|lower }}-{{ ansible_architecture|lower }}"
docker_machine_version: "0.13.0"
docker_compose_version: "1.18"

absent_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine
