---
docker_machine_package_name: "docker-machine-{{ ansible_system|lower }}-{{ ansible_architecture|lower }}"
docker_compose_version: "1.18"

absent_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine
