---
- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install necessary packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - aptitude
    - atop
    - bash-completion
    - build-essential
    - ca-certificates
    - curl
    - dnsmasq
    - dnsutils
    - git
    - glibc-doc
    - htop
    - iftop
    - jnettop
    - man-db
    - manpages
    - manpages-dev
    - mc
    - mercurial
    - net-tools
    - python
    - python-apt
    - python-dev
    - python-virtualenv
    - python3
    - python3-apt
    - python3-dev
    - python3-virtualenv
    - ruby
    - ruby-dev
    - rubygems
    - shellcheck
    - subversion
    - tig
    - tmux
    - traceroute
    - vim
    - w3m
    - wget

- name: install fpm package manager
  gem:
    name: fpm
    state: latest
    user_install: no

- name: generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8
    - cs_CZ.UTF-8

- name: setup correct time
  file:
    src: /usr/share/zoneinfo/Europe/Prague
    dest: /etc/localtime
    force: yes
    state: link

- name: make sshd listen only on ipv4
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ListenAddress 0.0.0.0"
    insertafter: "^#?ListenAddress 0.0.0.0"
    line: "ListenAddress 0.0.0.0"
  notify: ssh

- name: disable password auth in ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication yes|no"
    insertafter: "^#?PasswordAuthentication yes|no"
    line: "PasswordAuthentication no"
  notify: ssh
