- name: upgrade whole distro
  apt: upgrade=safe update_cache=yes cache_valid_time=3600

- name: install necessary packages
  apt: name={{ item }} state=latest
  with_items:
    - atop
    - aptitude
    - bash-completion
    - build-essential
    - ca-certificates
    - curl
    - dnsmasq
    - dnsutils
    - git
    - htop
    - iftop
    - jnettop
    - mc
    - mercurial
    - net-tools
    - python
    - python-apt
    - python-dev
    - python-virtualenv
    - python3
    - python3-apt
    - python3-dev
    - python3-virtualenv
    - ruby
    - ruby-dev
    - rubygems
    - subversion
    - tig
    - tmux
    - vim
    - wget

- name: install fpm package manager
  gem: name=fpm state=latest user_install=no

- name: generate locales
  locale_gen: name=en_US.UTF-8 state=present

- name: setup correct time
  file: src=/usr/share/zoneinfo/Europe/Prague dest=/etc/localtime force=yes state=link

- name: set NCURSES_NO_UTF8_ACS=1
  copy: dest=/etc/profile.d/ncurses_utf-8_fix.sh content="export NCURSES_NO_UTF8_ACS=1\n"

- name: install dnsmasq
  apt: name=dnsmasq state=latest

- name: configure dnsmasq
  copy: src=templates/dnsmasq.conf dest=/etc/dnsmasq.conf

- name: set resolv.conf nameserver to localhost
  copy: content="nameserver=127.0.0.1\n" dest=/etc/resolv.conf

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: install fail2ban
  apt: name=fail2ban state=latest

- name: configure fail2ban
  template:
    src: templates/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: restart fail2ban
  service: name=fail2ban state=restarted

