---
- name: set machine hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: enable epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- rpm_key:
    state: present
    key: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: install necessary packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - bash-completion
    - bash-completion-extras
    - bind-utils
    - ca-certificates
    - glibc-common
    - htop
    - iftop
    - man
    - man-pages
    - net-tools
    - ntp
    - python
    - python34
    - ruby
    - rubygems
    - traceroute

- name: setup correct time
  file:
    src: /usr/share/zoneinfo/Europe/Prague
    dest: /etc/localtime
    force: yes
    state: link

- name: make sshd listen only on ipv4
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ListenAddress 0.0.0.0"
    insertafter: "^#?ListenAddress 0.0.0.0"
    line: "ListenAddress 0.0.0.0"
  notify: ssh

- name: disable password auth in ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication yes|no"
    insertafter: "^#?PasswordAuthentication yes|no"
    line: "PasswordAuthentication no"
  notify: ssh

- name: service ntp is running
  service:
    name: nptd
    state: started
    enabled: true
  when: servercentric
