---
- name: install dnsmasq
  apt:
    name: dnsmasq
    state: latest

- name: configure dnsmasq
  copy:
    src: templates/dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: dnsmasq

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: install fail2ban
  apt:
    name: fail2ban
    state: latest

- name: configure fail2ban
  template:
    src: templates/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: fail2ban
