- name: create group for intended user
  group: name="{{ login }}"
  tags: user

- name: create intended user
  user:
    name: "{{ login }}"
    group: "{{ login }}"
    shell: /bin/bash
    home: "/home/{{ login }}"
  tags: user

- name: setup authorized_keys for all intended users
  authorized_key:
    user: "{{ item }}"
    key: "{{ ssh_pubkey }}"
    state: present
  with_items:
    - root
    - "{{ login }}"
  tags: user

- name: provision .gitconfig
  copy:
    content: "[user]\n\tname = {{ username }}\n\temail = {{ email }}\n[push]\n\tdefault = simple\n"
    dest: "{{ item }}"
  with_items:
    - /root/.gitconfig
    - "/home/{{ login }}/.gitconfig"
  tags: user

- name: setup bashrc
  template:
    dest: /etc/profile.d/bashrc.sh
    src: templates/bashrc
  tags: user

- name: provision .vimrc
  template:
    dest: "{{ item }}"
    src: templates/vimrc
  with_items:
    - /root/.vimrc
    - "/home/{{ login }}/.vimrc"
  tags: user

