- name: create group for intended user
  group:
    name: "{{ login }}"
  tags: user

- name: create intended user
  user:
    name: "{{ login }}"
    group: "{{ login }}"
    shell: /bin/bash
    home: "/home/{{ login }}"
  tags: user

- name: setup authorized_keys for all intended users
  authorized_key:
    user: "{{ item }}"
    key: "{{ ssh_pubkey }}"
    state: present
  with_items:
    - root
    - "{{ login }}"
  tags: user

- name: provision .gitconfig
  copy:
    content: "[user]\n\tname = {{ username }}\n\temail = {{ email }}\n[push]\n\tdefault = simple\n"
    dest: "{{ item }}"
  with_items:
    - /root/.gitconfig
    - "/home/{{ login }}/.gitconfig"
  tags: user

- name: setup bashrc
  template:
    dest: /etc/profile.d/bashrc.sh
    src: templates/bashrc
  tags: user

- name: provision .vimrc
  template:
    dest: "{{ item }}"
    src: templates/vimrc
  with_items:
    - /root/.vimrc
    - "/home/{{ login }}/.vimrc"
  tags: user

- name: prepare pathogen directories
  file:
    path: "{{ item }}"
    recurse: yes
  with_items:
    - /root/.vim/autoload
    - /root/.vim/bundle
    - /home/{{ login }}/.vim/autoload
    - /home/{{ login }}/.vim/bundle

- name: download pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ item  }}"
  with_items:
    - /root/.vim/autoload/pathogen.vim
    - /home/{{ login }}/.vim/autoload/pathogen.vim

- name: put syntastic into bundle directory
  git:
    repo: https://github.com/vim-syntastic/syntastic.git
    dest: "{{ item }}"
    update: yes
    depth: 1
  with_items:
    - /root/.vim/bundle/syntastic.git
    - /home/{{ login }}/.vim/bundle/syntastic.git

- name: put ansible syntax colors into bundle directory
  git:
    repo: https://github.com/pearofducks/ansible-vim
    dest: "{{ item }}"
    update: yes
  with_items:
    - /root/.vim/bundle/ansible-vim
    - /home/{{ login }}/.vim/bundle/ansible-vim
