---
- yum:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ packages }}"
  when: servercentric

- name: configure fail2ban
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
  notify: fail2ban
  when: servercentric

- name: configure dnsmasq
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.d/dnsmasq.conf
  notify: dnsmasq
  when: servercentric
