---
- yum:
    name: "{{ packages }}"
    state: latest

- name: configure fail2ban
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
  notify: fail2ban
  when: ignored_ips is defined

- name: start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  when: ignored_ips is defined

- name: setup SELinux
  selinux:
    state: "{{ selinux_policy }}"
  tags:
    - common
  when: ansible_virtualization_type != "docker"

- name: harden through sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { "name": "kernel.dmesg_restrict", "value": "1" }
    - { "name": "kernel.kptr_restrict", "value": "2" }
    - { "name": "kernel.sysrq", "value": "0" }
    - { "name": "kernel.yama.ptrace_scope", "value": "2" }
    - { "name": "net.ipv4.conf.all.forwarding", "value": "0" }
    - { "name": "net.ipv4.conf.all.log_martians", "value": "1" }
    - { "name": "net.ipv4.conf.all.accept_redirects", "value": "0" }
    - { "name": "net.ipv4.conf.all.send_redirects", "value": "0" }
    - { "name": "net.ipv4.conf.default.accept_redirects", "value": "0" }
    - { "name": "net.ipv4.conf.default.accept_source_route", "value": "0" }
    - { "name": "net.ipv4.conf.default.log_martians", "value": "1" }
    - { "name": "net.ipv6.conf.all.accept_redirects", "value": "0" }
    - { "name": "net.ipv6.conf.default.accept_redirects", "value": "0" }
