---
- yum:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ packages }}"

- name: configure fail2ban
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
  notify: fail2ban

- name: start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: setup SELinux
  selinux:
    state: "{{ selinux_policy }}"
  tags:
    - common
  when: ansible_virtualization_type != "docker"
