---
- name: install postfix
  yum:
    name: postfix
    state: present
  tags:
    - postfix

- name: configure postfix
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  loop:
    - { "src": "main.cf.j2", "dest": "/etc/postfix/main.cf" }
  tags:
    - postfix

- name: start postfix
  service:
    name: postfix
    state: started
    enabled: yes
  tags:
    - postfix
