---
- name: install postfix
  yum:
    name: postfix
    state: present

- name: configure postfix
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  loop:
    - { "src": "main.cf.j2", "dest": "/etc/postfix/main.cf" }

- name: start postfix
  service:
    name: postfix
    state: started
    enabled: yes
