- name: Restart ssh
  ansible.builtin.systemd:
    name: sshd
    daemon_reload: true
    state: reloaded
    enabled: true
  when: ansible_virtualization_type != "docker"

- name: Dnf clean
  ansible.builtin.command: dnf clean all
