- name: ssh
  systemd:
    name: sshd
    daemon_reload: yes
    state: reloaded
    enabled: yes
  when: ansible_virtualization_type != "docker"

- name: ntp
  service:
    name: ntpd
    state: started
    enabled: yes

- name: yum clean
  command: yum clean all
  args:
    warn: no
