---
- name: docker
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: versionlock docker
  command: yum versionlock "{{ docker_package_name }}-{{ docker_version_centos }}"
  when: ansible_distribution == "CentOS"
  args:
    warn: no
