---
- name: Enable and start ssh-agent service
  ansible.builtin.systemd:
    name: ssh-agent
    state: restarted
    scope: user
    enabled: true
    daemon_reload: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[{{ user.login }}].1 }}"
