---
- name: yum
  yum:
    name: "{{ packages }}"
    state: present

- name: configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify: restart network
  when: ansible_virtualization_type != "docker"

- name: configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: dnsmasq

- name: start dnsmasq daemon
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: download hosts.ads file
  get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    dest: /etc/hosts.ads
    owner: root
    group: root
    mode: 0644
  when: adblock|bool

- name: restart dnsmasq daemon
  service:
    name: dnsmasq
    state: restarted

- name: setup nameserver to 127.0.0.1
  copy:
    content: "nameserver 127.0.0.1\n"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_virtualization_type != "docker"
