---
- name: yum
  yum:
    name: "{{ packages }}"
    state: present
  tags:
    - network

- name: configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify: restart network
  when: ansible_virtualization_type != "docker"
  tags:
    - network

- name: configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: dnsmasq
  tags:
    - network

- name: download hosts.ads file
  get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    dest: /etc/hosts.ads
    owner: root
    group: root
    mode: 0644
  when: adblock|bool
  tags:
    - network

- name: start dnsmasq daemon
  systemd:
    name: dnsmasq
    state: started
    enabled: yes
  when: ansible_virtualization_type != "docker"
  tags:
    - network

- name: setup nameserver to 127.0.0.1
  copy:
    content: "nameserver 127.0.0.1\n"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_virtualization_type != "docker"
  tags:
    - network

- name: setup ufw default incoming policy
  ufw:
    policy: deny
    direction: incoming
  notify: reload ufw
  when: ansible_virtualization_type != "docker"
  tags:
    - network

- name: setup ufw default outgoing policy
  ufw:
    policy: allow
    direction: outgoing
  notify: reload ufw
  when: ansible_virtualization_type != "docker"
  tags:
    - network

- name: allow ssh in ufw
  ufw:
    rule: allow
    name: ssh
  notify: reload ufw
  when: ansible_virtualization_type != "docker"
  tags:
    - network
