---
- name: yum
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ packages }}"
  when: ansible_distribution == "CentOS" and servercentric
    
- name: disable ipv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  when: not ipv6

- name: disable ipv6
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  when: ipv6

- name: configure /etc/hosts
  template:
    src: hosts
    dest: /etc/hosts

- name: configure dnsmasq
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: dnsmasq
  when: servercentric

- name: download hosts.ads file
  get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    dest: /etc/hosts.ads
    owner: root
    group: root
    mode: 0644
  when: adblock

- name: start dnsmasq
  service:
    name: dnsmasq
    state: started

- name: setup nameserver to 127.0.0.1
  copy:
    content: "nameserver 127.0.0.1\n"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
