---
- name: yum
  yum:
    name: "{{ packages }}"
    state: present
    
- name: disable ipv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  notify: restart network
  when: not ipv6.enabled

- name: enable ipv6
  sysctl:
    name: "{{ item }}"
    value: 0
    sysctl_set: yes
    state: present
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  notify: restart network
  when: ipv6.enabled

- name: enable NETWORKING_IPV6
  lineinfile:
    regexp: "^#?NETWORKING_IPV6"
    line: "NETWORKING_IPV6=yes"
    path: /etc/sysconfig/network
  notify: restart network
  when: ipv6.enabled

- name: enable NETWORKING_IPV6
  lineinfile:
    regexp: "^#?NETWORKING_IPV6"
    line: "NETWORKING_IPV6=no"
    path: /etc/sysconfig/network
  notify: restart network
  when: not ipv6.enabled

- name: configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify: restart network
  when: ansible_virtualization_type != "docker"

- name: configure /etc/sysconfig/network-scripts
  template:
    src: ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644
  notify: restart network

- name: configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: dnsmasq

- name: start dnsmasq daemon
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: download hosts.ads file
  get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    dest: /etc/hosts.ads
    owner: root
    group: root
    mode: 0644
  when: adblock

- name: start dnsmasq
  service:
    name: dnsmasq
    state: started

- name: setup nameserver to 127.0.0.1
  copy:
    content: "nameserver 127.0.0.1\n"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_virtualization_type != "docker"
