- name: ssh
  systemd:
    name: sshd
    enabled: yes
    daemon_reload: yes
    state: reloaded
  when: servercentric
- name: ntp
  service:
    name: ntpd
    state: started
    enabled: true
  when: servercentric
- name: yum clean
  command: yum clean all
- name: openvpn
  systemd:
    name: openvpn
    enabled: yes
    daemon_reload: yes
    state: restarted
