- name: ssh
  systemd:
    name: sshd
    daemon_reload: yes
    state: reloaded
    enabled: yes

- name: ntp
  service:
    name: ntpd
    state: started
    enabled: yes

- name: yum clean
  command: yum clean all
  warn: no
