#!/bin/bash

if [ ${UID} == 0 ]; then ENDING="#"; else ENDING="$"; fi

source /usr/share/git-core/contrib/completion/git-prompt.sh
export PS1="${debian_chroot:+($debian_chroot)}\u@\H:\w\$(__git_ps1 ':%s') ${ENDING} "

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -alF'
alias la='ls -A'

# some usefull functions
extract () {
  if [ -f "$1" ] ; then
      case $1 in
          *.tar.bz2)   tar xvjf "$1"    ;;
          *.tar.gz)    tar xvzf "$1"    ;;
          *.bz2)       bunzip2 "$1"     ;;
          *.rar)       rar x "$1"       ;;
          *.gz)        gunzip "$1"      ;;
          *.tar)       tar xvf "$1"     ;;
          *.tbz2)      tar xvjf "$1"    ;;
          *.tgz)       tar xvzf "$1"    ;;
          *.zip)       unzip "$1"       ;;
          *.Z)         uncompress "$1"  ;;
          *.7z)        7z x "$1"        ;;
          *)           echo "don't know how to extract '$1'..." ;;
      esac
  else
      echo "'$1' is not a valid file!"
  fi
}

docker-cleanup () {
  echo "Deleting all stopped containers"
  docker ps -a -q | xargs -r docker rm
  echo "Deleting dangling images"
  docker volume ls -qf dangling=true | xargs -r docker volume rm
}
