execute pathogen#infect()

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

set number 
set showmode
set nocompatible
set backspace=2
syntax on
set fileencodings=utf-8,latin2
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

colorscheme desert
