---
- name: Add yum repository for docker
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  tags:
    - docker

- name: Install required packages for docker
  ansible.builtin.dnf:
    name: "{{ item }}"
  loop: "{{ packages }}"
  notify: Restart docker
  tags:
    - docker
