---
- name: add yum repository for docker
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  tags:
    - docker

- name: install required packages for docker
  yum:
    name: "{{ item }}"
  loop: "{{ packages }}"
  notify: restart docker
  tags:
    - docker