---
- name: install required packages for docker
  yum:
    name: "{{ item }}"
  loop: "{{ packages }}"

- name: add yum repository for docker
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- rpm_key:
    key: https://download.docker.com/linux/centos/gpg

- name: install docker-ce
  yum:
    name: docker-ce
    state: present
  notify:
    - docker

- name: setup /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: provision daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - docker

- name: start docker daemon
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_virtualization_type != "docker"

- name: docker-compose present
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
