---
- name: Add yum repository for docker
  ansible.builtin.template:
    src: docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: "0644"
  when: docker_enabled is defined and docker_enabled is true
  tags:
    - docker

- name: Install required packages for docker
  ansible.builtin.dnf:
    name: "{{ item }}"
  loop: "{{ packages }}"
  when: docker_enabled is defined and docker_enabled is true
  tags:
    - docker

- name: Enable docker service upon start
  ansible.builtin.systemd:
    name: docker
    enabled: true
  when: docker_enabled is defined and docker_enabled is true
  tags:
    - docker
