---
- name: remove repos we don't need
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ absent_repos }}"
  when: yum_cleanup

- name: enable epel repo
  yum:
    name: epel-release
  when: ansible_distribution == "CentOS"
  notify: yum clean

- name: install necessary packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    "{{ base_packages }} "
  when: ansible_distribution == "CentOS"
  notify: yum clean

- name: set machine hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined and ansible_virtualization_type != "docker"

- name: setup correct time
  file:
    src: /usr/share/zoneinfo/Europe/Prague
    dest: /etc/localtime
    force: yes
    state: link
  notify: ntp

- name: make sshd listen only on ipv4
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ListenAddress 0.0.0.0"
    insertafter: "^#?ListenAddress 0.0.0.0"
    line: "ListenAddress 0.0.0.0"
  notify: ssh

- name: disable password auth in ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication (yes|no)"
    insertafter: "^#PasswordAuthentication (yes|no)"
    line: "PasswordAuthentication no"
  notify: ssh
