---
- name: Enable epel repo
  ansible.builtin.dnf:
    name: epel-release
  notify: Dnf clean
  tags:
    - base

- name: Install necessary packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  notify: Dnf clean
  tags:
    - base

- name: Set machine hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: hostname is defined and wsl2 is false
  tags:
    - base

- name: Setup timezone
  community.general.timezone:
    name: Europe/Prague
  tags:
    - base

- name: Configure sshd
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    user: root
    group: root
    mode: 0600
  when: wsl2 is false
  notify: Restart ssh
  tags:
    - base
