---
- name: enable epel repo
  dnf:
    name: epel-release
  notify: dnf clean
  tags:
    - base

- name: install necessary packages
  dnf:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  notify: dnf clean
  tags:
    - base

- name: set machine hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined and ansible_virtualization_type != "docker"
  tags:
    - base

- name: setup timezone
  timezone:
    name: Europe/Prague
    hwclock: local
  tags:
    - base

- name: configure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: ssh
  tags:
    - base
