---
- name: Prepare pathogen directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ login }}"
    group: "{{ login }}"
    mode: 0700
  loop:
    - /home/{{ login }}/.vim
    - /home/{{ login }}/.vim/autoload
    - /home/{{ login }}/.vim/plugged
  tags:
    - vim

- name: Install vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ item }}"
    owner: "{{ login }}"
    group: "{{ login }}"
    mode: 0500
  when: not ansible_check_mode
  loop:
    - /home/{{ login }}/.vim/autoload/plug.vim
  tags:
    - vim

- name: Provision .vimrc
  ansible.builtin.template:
    dest: "{{ item }}"
    src: vimrc
    owner: "{{ login }}"
    group: "{{ login }}"
    mode: 0600
  loop:
    - "/home/{{ login }}/.vimrc"
    - "/root/.vimrc"
  tags:
    - vim
