---
- name: prepare pathogen directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ login }}"
    group: "{{ login }}"
  loop:
    - /home/{{ login }}/.vim/autoload
    - /home/{{ login }}/.vim/bundle

- name: download pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ item  }}"
    owner: "{{ login }}"
    group: "{{ login }}"
  loop:
    - /home/{{ login }}/.vim/autoload/pathogen.vim

- name: put plugins into bundle directory
  git:
    repo: "{{ item }}"
    dest: "/home/{{ login }}/.vim/bundle/{{ item.split('/')[4] }}"
    update: yes
    depth: 1
  when: vim_plugins is defined
  loop: "{{ vim_plugins }}"

- name: set correct permissions on vim plugins
  file:
    path: "/home/{{ login }}/.vim/bundle"
    owner: "{{ login }}"
    group: "{{ login }}"
    recurse: yes

- name: provision .vimrc
  template:
    dest: "{{ item }}"
    src: vimrc
    owner: "{{ login }}"
    group: "{{ login }}"
  loop:
    - "/home/{{ login }}/.vimrc"
