---
- name: prepare pathogen directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - /root/.vim/autoload
    - /root/.vim/bundle
    - /home/{{ login }}/.vim/autoload
    - /home/{{ login }}/.vim/bundle

- name: download pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ item  }}"
  loop:
    - /root/.vim/autoload/pathogen.vim
    - /home/{{ login }}/.vim/autoload/pathogen.vim

- name: put plugins into bundle directory
  git:
    repo: "{{ item }}"
    dest: "/home/{{ login }}/.vim/bundle/{{ item.split('/')[4] }}"
    update: yes
    depth: 1
  when: vim_plugins is defined
  loop: "{{ vim_plugins }}"

- name: provision .vimrc
  template:
    dest: "{{ item }}"
    src: vimrc
  loop:
    - /root/.vimrc
    - "/home/{{ login }}/.vimrc"
