---
- name: fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    daemon_reload: yes
    state: restarted
  when: servercentric

- name: privoxy
  systemd:
    name: privoxy
    enabled: yes
    daemon_reload: yes
    state: restarted
  when: servercentric
