---
- name: fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    daemon_reload: yes
    state: restarted
  when: ansible_virtualization_type != "docker"

- name: privoxy
  systemd:
    name: privoxy
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: dnsmasq
  systemd:
    name: dnsmasq
    enabled: yes
    daemon_reload: yes
    state: restarted
